[project]
name = "grounding-dino"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "detection-viewer",
    "torch==2.9.1",
    "transformers>=5.1.0",
]

[tool.uv.sources]
detection-viewer = { path = "../../", editable = true }

[dependency-groups]
dev = [
    "ruff>=0.15.1",
]

[tool.ruff]
extend = "../../pyproject.toml"

[tool.ruff.lint.per-file-ignores]
"app.py" = ["INP001"]
